services:
  ubuntu-desktop-lxde-vnc:
    ports:
      - '6080:80'
    volumes:
            - '/dev/shm:/dev/shm'
    image: dorowu/ubuntu-desktop-lxde-vnc 
  slasdm:
    build: .
    restart: on-failure
    ports:
      - '443:443' 
